server:
  port: 5002

spring:
  application:
    name: TASK-SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:mysql://localhost:3306/ontrack_task_db'
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
